// Default fallback data used when database is not configured (e.g., on first Vercel deploy without DB).
// Once DATABASE_URL is set and seeded, the site reads from DB instead.

export const defaultSettings = {
  id: 1,
  siteNameAr: "مريم",
  siteNameEn: "Maryam",
  logoLetter: "M",
  taglineAr: "بصريات سينمائية تلتقط الروح اليمنية والعالمية",
  taglineEn: "Yemeni Visual Storyteller",
  heroTitleAr: "مريم",
  heroSubtitleEn: "M·A·R·Y·A·M",
  heroDescAr:
    "أصوّر ما لا يُرى. أنتقل بالعدسة بين ضوء صنعاء القديمة وظلال العالم، لألتقط اللحظات التي تستحق أن تُروى.",
  heroCta1Ar: "استكشف الأعمال",
  heroCta2Ar: "قصة مريم",
  heroStat1Num: "+250",
  heroStat1Label: "جلسة تصوير",
  heroStat2Num: "+7",
  heroStat2Label: "سنوات خبرة",
  heroStat3Num: "+40",
  heroStat3Label: "جائزة وتكريم",
  marqueeWords:
    "بورتريه,Portraits,أعراس,Weddings,ثقافة,Culture,مناظر,Landscapes,صنعاء,Sana'a,عدن,Aden",
  aboutTitleAr: "قصة خلف العدسة",
  aboutSubtitleEn: "About the Artist",
  aboutHeadingAr: "من سردات صنعاء إلى عدسة العالم",
  aboutPara1:
    "وُلدت مريم في قلب صنعاء القديمة، حيث يتنفس التراب ضوءًا ذهبيًا مع كل غروب. حملت أول كاميرا في الخامسة عشرة من عمرها، ومنذ ذلك اليوم لم تعد العدسة أداةً بل امتدادًا لروحها.",
  aboutPara2:
    "درست الفنون البصرية في دبي، وعملت لاحقًا مع منصات دولية مثل National Geographic Arabia و Magnum Photos. لكنها بقيت وفية لجذورها.",
  aboutTags: "بورتريه,تصوير أعراس,تصوير ثقافي,فوتوجورناليزم,تصوير معماري",
  aboutSignature: "~ مريم",
  portfolioTitleAr: "معرض الأعمال",
  portfolioSubtitleEn: "Selected Works",
  servicesTitleAr: "خدمات التصوير",
  servicesSubtitleEn: "Services & Packages",
  testimonialsTitleAr: "آراء العملاء",
  testimonialsSubtitleEn: "Client Voices",
  contactTitleAr: "لنبدأ حكايتك",
  contactSubtitleEn: "Let's Create Together",
  contactEmail: "hello@maryam.photo",
  contactPhone: "+967 77 123 4567",
  contactAddress: "صنعاء القديمة · اليمن",
  contactInstagram: "#",
  contactWhatsapp: "#",
  footerDesc:
    "بصريات سينمائية من قلب صنعاء. أصوّر الحكايات قبل الأشخاص، وألتقط في كل إطار لحظة تستحق أن تُروى.",
  footerCopyright: "© 2024 مريم. جميع الحقوق محفوظة.",
  primaryColor: "oklch(0.82 0.12 80)",
  backgroundColor: "oklch(0.08 0.005 285)",
};

export const defaultPhilosophy = [
  {
    id: 1,
    icon: "Camera",
    titleAr: "بصمة بصرية",
    titleEn: "Signature",
    descAr:
      "كل صورة تُحمل بصمتي السينمائية: ضوء دافئ، ظلال عميقة، وحكاية تُروى قبل أن يلمحها الناظر.",
    order: 1,
  },
  {
    id: 2,
    icon: "Globe2",
    titleAr: "جذور يمنية",
    titleEn: "Yemeni Roots",
    descAr:
      "أصيل من صنعاء القديمة. أنقل تراث اليمن المعماري والإنساني إلى مشهد بصري عالمي معاصر.",
    order: 2,
  },
  {
    id: 3,
    icon: "Award",
    titleAr: "تكريم دولي",
    titleEn: "Recognition",
    descAr:
      "أعمالي عُرضت في معارض دبي، إسطنبول، وبرلين. حائزة على جوائز Sony World Photography و National Geographic Yemen.",
    order: 3,
  },
  {
    id: 4,
    icon: "Heart",
    titleAr: "روح الإنسان",
    titleEn: "Human Soul",
    descAr:
      "أبحث دائمًا عن اللحظة العفوية التي تنسى فيها الكاميرا — حين يظهر الناس كما هم حقًا.",
    order: 4,
  },
];

export const defaultProjects = [
  {
    id: 1,
    titleAr: "عروس صنعاء",
    titleEn: "Bride of Sana'a",
    category: "weddings",
    year: "2024",
    location: "صنعاء القديمة",
    description: "صورة من سلسلة تصوير الأعراس في صنعاء القديمة.",
    imageData: "",
    palette1: "oklch(0.4 0.1 40)",
    palette2: "oklch(0.2 0.05 285)",
    palette3: "oklch(0.78 0.13 75)",
    motif: "bride",
    span: "tall",
    featured: false,
    order: 1,
    published: true,
  },
  {
    id: 2,
    titleAr: "وجه من حضرموت",
    titleEn: "A Face from Hadramaut",
    category: "portraits",
    year: "2024",
    location: "تريم",
    description: "بورتريه من وادي حضرموت.",
    imageData: "",
    palette1: "oklch(0.5 0.08 50)",
    palette2: "oklch(0.15 0.02 30)",
    palette3: "oklch(0.85 0.1 80)",
    motif: "face",
    span: "wide",
    featured: false,
    order: 2,
    published: true,
  },
  {
    id: 3,
    titleAr: "أبراج اليمن",
    titleEn: "Yemeni Towers",
    category: "culture",
    year: "2023",
    location: "شبام حضرموت",
    description: "عمارة طينية فريدة في شبام.",
    imageData: "",
    palette1: "oklch(0.55 0.12 60)",
    palette2: "oklch(0.25 0.05 40)",
    palette3: "oklch(0.9 0.08 80)",
    motif: "tower",
    span: "normal",
    featured: false,
    order: 3,
    published: true,
  },
  {
    id: 4,
    titleAr: "صحراء الربع الخالي",
    titleEn: "Empty Quarter",
    category: "landscapes",
    year: "2023",
    location: "حدود المهرة",
    description: "كثبان رملية عند الغروب.",
    imageData: "",
    palette1: "oklch(0.6 0.1 55)",
    palette2: "oklch(0.3 0.05 35)",
    palette3: "oklch(0.85 0.12 75)",
    motif: "desert",
    span: "wide",
    featured: false,
    order: 4,
    published: true,
  },
];

export const defaultServices = [
  {
    id: 1,
    titleAr: "تصوير الأعراس",
    titleEn: "Wedding Photography",
    description: "تغطية كاملة ليوم العرس بأسلوب سينمائي راقٍ.",
    price: "يبدأ من 1,200$",
    duration: "8 ساعات",
    features: JSON.stringify([
      "تغطية كاملة لليوم",
      "جلسة قبل العرس",
      "300 صورة معدلة",
      "ألبوم فاخر مطبوع",
    ]),
    icon: "Heart",
    accentFrom: "oklch(0.78 0.13 75 / 0.15)",
    featured: true,
    order: 1,
    published: true,
  },
  {
    id: 2,
    titleAr: "بورتريه فردي",
    titleEn: "Portrait Sessions",
    description: "جلسة بورتريه شخصية.",
    price: "يبدأ من 350$",
    duration: "2 ساعة",
    features: JSON.stringify([
      "جلسة في الاستوديو أو خارجي",
      "50 صورة معدلة",
      "حقوق استخدام كاملة",
    ]),
    icon: "Camera",
    accentFrom: "oklch(0.55 0.1 40 / 0.12)",
    featured: false,
    order: 2,
    published: true,
  },
];

export const defaultTestimonials = [
  {
    id: 1,
    quoteAr:
      "مريم لم تُصور زفافنا فحسب، بل التقطت أرواحنا. كل صورة تحكي حكاية كاملة.",
    nameAr: "أحمد و سارة المطري",
    roleAr: "عرسان · صنعاء",
    roleEn: "Newlyweds",
    rating: 5,
    avatar: "أ س",
    order: 1,
    published: true,
  },
  {
    id: 2,
    quoteAr:
      "كعلامة تجارية، كنا نبحث عن صورة تعبّر عن هويتنا اليمنية بأسلوب عالمي. مريم فهمت الرؤية فورًا.",
    nameAr: "ليلى العنسي",
    roleAr: "مديرة تسويق · Yemen Heritage",
    roleEn: "Marketing Director",
    rating: 5,
    avatar: "ل ع",
    order: 2,
    published: true,
  },
];
